[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.

# Actually tell PEP517 tools to call setuptools
build-backend = "setuptools.build_meta"
